<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<!DOCTYPE html>
<html lang="ko">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>인사관리 &gt; 인사기록카드</title>
<link rel="stylesheet" href="${pageContext.request.contextPath}/css/employees/employees-record-card.css">
<link rel="stylesheet" href="${pageContext.request.contextPath}/css/common/payzon-ui.css">
</head>
<body>
	<%@ include file="/WEB-INF/view/common/header.jspf" %>
	<main class="page-content">
		<div class="record-page">
			<header class="page-heading"><div><p>인사관리</p><h1>인사기록카드</h1></div></header>

			<%-- 부서, 직위, 이름 조건으로 사원 선택 목록을 서버에서 다시 조회한다. --%>
			<form class="employee-search" action="${pageContext.request.contextPath}/personnel/employee-card.do#employee-select-modal" method="get">
				<select name="departmentId"><option value="">전체 부서</option><c:forEach var="department" items="${departments}"><option value="${department.departmentId}" ${param.departmentId eq department.departmentId ? 'selected' : ''}><c:out value="${department.departmentName}" /></option></c:forEach></select>
				<select name="positionId"><option value="">전체 직위</option><c:forEach var="position" items="${positions}"><option value="${position.jobPositionId}" ${param.positionId eq position.jobPositionId ? 'selected' : ''}><c:out value="${position.jobPositionName}" /></option></c:forEach></select>
				<input name="keyword" value="<c:out value='${param.keyword}' />" placeholder="검색어 입력">
				<button class="search-button" type="submit">검색</button>
				<a class="all-view" href="${pageContext.request.contextPath}/personnel/employee-card.do">전체보기</a>
			</form>

			<%-- 선택된 EMPLOYEE와 사원별 상세 이력을 인사기록카드 형식으로 출력한다. --%>
			<article class="record-sheet">
				<section class="identity-section">
					<div class="photo-box"><c:choose><c:when test="${not empty selectedEmployee.photoPath}"><img src="<c:out value='${selectedEmployee.photoPath}' />" alt="사원사진"></c:when><c:otherwise><span>사진</span></c:otherwise></c:choose></div>
					<dl class="record-number"><div><dt>사원번호</dt><dd><c:out value="${selectedEmployee.empNo}" /></dd></div><div><dt>입사일</dt><dd><fmt:formatDate value="${selectedEmployee.joinDate}" pattern="yyyy-MM-dd" /></dd></div><div><dt>퇴사일</dt><dd><fmt:formatDate value="${selectedEmployee.retireDate}" pattern="yyyy-MM-dd" /></dd></div></dl>
					<dl class="identity-grid"><div><dt>성명(한글)</dt><dd><c:out value="${selectedEmployee.empNameKr}" /></dd></div><div><dt>성명(영문)</dt><dd><c:out value="${selectedEmployee.empNameEn}" /></dd></div><div><dt>주민등록번호</dt><dd><c:if test="${fn:length(selectedEmployee.juminNo) ge 6}"><c:out value="${fn:substring(selectedEmployee.juminNo, 0, 6)}-*******" /></c:if></dd></div><div><dt>사원구분</dt><dd><c:out value="${selectedEmployee.empType}" /></dd></div><div class="wide"><dt>주소</dt><dd><c:out value="${selectedEmployee.address}" /></dd></div><div><dt>휴대전화</dt><dd><c:out value="${selectedEmployee.mobileNo}" /></dd></div><div><dt>연락처</dt><dd><c:out value="${selectedEmployee.telNo}" /></dd></div><div class="wide"><dt>E-Mail</dt><dd><c:out value="${selectedEmployee.email}" /></dd></div></dl>
				</section>

				<div class="family-insurance-layout">
					<section class="record-section"><h3>가족사항</h3><table><thead><tr><th>관계</th><th>성명</th><th>주민등록번호</th><th>동거여부</th></tr></thead><tbody><c:forEach var="family" items="${families}"><tr><td><c:out value="${family.relation}" /></td><td><c:out value="${family.depName}" /></td><td>******-*******</td><td><c:out value="${family.cohabitYn eq 'Y' ? '동거' : '비동거'}" /></td></tr></c:forEach><c:if test="${empty families}"><c:forEach begin="1" end="4"><tr class="blank-row"><td></td><td></td><td></td><td></td></tr></c:forEach></c:if></tbody></table></section>
					<section class="record-section"><h3>4대보험</h3><table><thead><tr><th>구분</th><th>기호번호</th><th>취득일</th><th>상실일</th></tr></thead><tbody><c:forEach var="insurance" items="${insurances}"><tr><td><c:out value="${insurance.insuranceType}" /></td><td><c:out value="${insurance.symbolNo}" /></td><td><fmt:formatDate value="${insurance.acquireDate}" pattern="yyyy-MM-dd" /></td><td><fmt:formatDate value="${insurance.lossDate}" pattern="yyyy-MM-dd" /></td></tr></c:forEach><c:if test="${empty insurances}"><c:forEach var="insuranceName" items="국민연금,건강보험,고용보험,산재보험"><tr><td><c:out value="${insuranceName}" /></td><td></td><td></td><td></td></tr></c:forEach></c:if></tbody></table></section>
				</div>

				<section class="record-section"><h3>학력</h3><table><thead><tr><th>학교명</th><th>입학년월</th><th>졸업년월</th><th>전공</th><th>이수</th></tr></thead><tbody><c:forEach var="education" items="${educations}"><tr><td><c:out value="${education.schoolName}" /></td><td><c:out value="${education.admissionYm}" /></td><td><c:out value="${education.gradYm}" /></td><td><c:out value="${education.majorName}" /></td><td><c:out value="${education.completeType}" /></td></tr></c:forEach><c:if test="${empty educations}"><c:forEach begin="1" end="2"><tr class="blank-row"><td></td><td></td><td></td><td></td><td></td></tr></c:forEach></c:if></tbody></table></section>
				<section class="record-section"><h3>병역</h3><table><thead><tr><th>제대구분</th><th>미필사유</th><th>군별</th><th>최종계급</th><th>병과</th><th>복무기간</th></tr></thead><tbody><tr><td><c:out value="${selectedEmployee.dischargeType}" /></td><td><c:out value="${selectedEmployee.milUnfinishedReason}" /></td><td><c:out value="${selectedEmployee.milBranch}" /></td><td><c:out value="${selectedEmployee.milRank}" /></td><td><c:out value="${selectedEmployee.milSpecialty}" /></td><td><fmt:formatDate value="${selectedEmployee.milServiceStart}" pattern="yyyy-MM-dd" /> ~ <fmt:formatDate value="${selectedEmployee.milServiceEnd}" pattern="yyyy-MM-dd" /></td></tr></tbody></table></section>
				<section class="record-section"><h3>경력</h3><table><thead><tr><th>회사명</th><th>입사일자</th><th>퇴사일자</th><th>최종직위</th><th>담당업무</th></tr></thead><tbody><c:forEach var="career" items="${careers}"><tr><td><c:out value="${career.companyName}" /></td><td><fmt:formatDate value="${career.joinDate}" pattern="yyyy-MM-dd" /></td><td><fmt:formatDate value="${career.quitDate}" pattern="yyyy-MM-dd" /></td><td><c:out value="${career.finalPosition}" /></td><td><c:out value="${career.duty}" /></td></tr></c:forEach><c:if test="${empty careers}"><tr class="blank-row"><td colspan="5"></td></tr><tr class="blank-row"><td colspan="5"></td></tr></c:if></tbody></table></section>

				<div class="double-section">
					<section class="record-section"><h3>자격/면허</h3><table><thead><tr><th>종류</th><th>취득일</th><th>발행기관</th><th>비고</th></tr></thead><tbody><c:forEach var="license" items="${licenses}"><tr><td><c:out value="${license.licName}" /></td><td><fmt:formatDate value="${license.acqDate}" pattern="yyyy-MM-dd" /></td><td><c:out value="${license.issuer}" /></td><td><c:out value="${license.note}" /></td></tr></c:forEach><c:if test="${empty licenses}"><tr class="blank-row"><td colspan="4"></td></tr><tr class="blank-row"><td colspan="4"></td></tr></c:if></tbody></table></section>
					<section class="record-section"><h3>어학능력</h3><table><thead><tr><th>외국어명</th><th>시험</th><th>공인점수</th><th>취득일</th><th>독해</th><th>작문</th><th>회화</th></tr></thead><tbody><c:forEach var="language" items="${languages}"><tr><td><c:out value="${language.langName}" /></td><td><c:out value="${language.testName}" /></td><td><c:out value="${language.score}" /></td><td><fmt:formatDate value="${language.acqDate}" pattern="yyyy-MM-dd" /></td><td><c:out value="${language.readingLevel}" /></td><td><c:out value="${language.writingLevel}" /></td><td><c:out value="${language.speakingLevel}" /></td></tr></c:forEach><c:if test="${empty languages}"><tr class="blank-row"><td colspan="7"></td></tr><tr class="blank-row"><td colspan="7"></td></tr></c:if></tbody></table></section>
				</div>

				<section class="record-section"><h3>교육사항</h3><table><thead><tr><th>교육구분</th><th>교육명</th><th>기간(부터)</th><th>기간(까지)</th><th>교육기관</th><th>교육비</th><th>환급교육비</th></tr></thead><tbody><c:forEach var="training" items="${trainings}"><tr><td><c:out value="${training.trainType}" /></td><td><c:out value="${training.trainName}" /></td><td><fmt:formatDate value="${training.startDate}" pattern="yyyy-MM-dd" /></td><td><fmt:formatDate value="${training.endDate}" pattern="yyyy-MM-dd" /></td><td><c:out value="${training.trainInstitute}" /></td><td><fmt:formatNumber value="${training.trainCost}" /></td><td><fmt:formatNumber value="${training.refundCost}" /></td></tr></c:forEach><c:if test="${empty trainings}"><tr class="blank-row"><td colspan="7"></td></tr><tr class="blank-row"><td colspan="7"></td></tr></c:if></tbody></table></section>
				<section class="record-section"><h3>상벌사항</h3><table><thead><tr><th>구분</th><th>상벌명</th><th>상벌권자</th><th>상벌일자</th><th>상벌내용</th><th>비고</th></tr></thead><tbody><c:forEach var="award" items="${awards}"><tr><td><c:out value="${award.rpType}" /></td><td><c:out value="${award.rpName}" /></td><td><c:out value="${award.rpAuthority}" /></td><td><fmt:formatDate value="${award.rpDate}" pattern="yyyy-MM-dd" /></td><td><c:out value="${award.rpContent}" /></td><td><c:out value="${award.note}" /></td></tr></c:forEach><c:if test="${empty awards}"><tr class="blank-row"><td colspan="6"></td></tr><tr class="blank-row"><td colspan="6"></td></tr></c:if></tbody></table></section>
				<section class="record-section"><h3>인사발령</h3><table><thead><tr><th>발령구분</th><th>발령일자</th><th>부서</th><th>직위</th><th>직책 및 담당업무</th><th>비고</th></tr></thead><tbody><c:forEach var="appointment" items="${appointments}"><tr><td><c:out value="${appointment.appType}" /></td><td><fmt:formatDate value="${appointment.appDate}" pattern="yyyy-MM-dd" /></td><td><c:out value="${appointment.departmentName}" /></td><td><c:out value="${appointment.jobPositionName}" /></td><td><c:out value="${appointment.jobTitleDuty}" /></td><td><c:out value="${appointment.note}" /></td></tr></c:forEach><c:if test="${empty appointments}"><tr class="blank-row"><td colspan="6"></td></tr><tr class="blank-row"><td colspan="6"></td></tr></c:if></tbody></table></section>
				<section class="record-section"><h3>퇴직사항</h3><table><thead><tr><th>퇴직구분</th><th>퇴직일자</th><th>퇴직사유</th><th>퇴직금</th><th>퇴직 후 연락처</th></tr></thead><tbody><tr><td><c:out value="${selectedEmployee.retireType}" /></td><td><fmt:formatDate value="${selectedEmployee.retireDate}" pattern="yyyy-MM-dd" /></td><td><c:out value="${selectedEmployee.retireReason}" /></td><td><c:if test="${not empty retirementCalculations}"><fmt:formatNumber value="${retirementCalculations[0].actualPayAmt}" /></c:if></td><td><c:out value="${selectedEmployee.afterRetireContact}" /></td></tr></tbody></table></section>
				<footer class="record-footer"><label><input type="checkbox" name="showCeo" checked> 대표자 표기</label><div class="record-footer__company"><strong><c:out value="${company.cmpnName}" /></strong><span><c:out value="${company.ceoTitle}" /> <c:out value="${company.ceoName}" /></span></div><div class="record-footer__stamp"><c:choose><c:when test="${not empty company.stampImgPath}"><img src="<c:out value='${company.stampImgPath}' />" alt="회사 도장"></c:when><c:otherwise><span>회사 도장을<br>넣어주세요</span></c:otherwise></c:choose></div></footer>
			</article>

			<div id="employee-select-modal" class="employee-modal" role="dialog" aria-modal="true" aria-labelledby="employee-modal-title"><a class="employee-modal__backdrop" href="#" aria-label="닫기"></a><form class="employee-modal__panel" action="${pageContext.request.contextPath}/personnel/employee-card.do" method="get"><div class="employee-modal__title"><h2 id="employee-modal-title">인사기록카드 사원선택</h2><a href="#" aria-label="닫기">×</a></div><div class="employee-modal__table"><table><thead><tr><th>구분</th><th>사원번호</th><th>성명</th><th>부서</th><th>직위</th><th>상태</th></tr></thead><tbody><c:forEach var="employee" items="${employees}" varStatus="loop"><tr><td><label for="employee-${loop.index}"><input id="employee-${loop.index}" type="radio" name="employeeId" value="${employee.employeeId}" required><span><c:out value="${employee.employmentType}" /></span></label></td><td><label for="employee-${loop.index}"><c:out value="${employee.employeeNo}" /></label></td><td><label for="employee-${loop.index}"><c:out value="${employee.name}" /></label></td><td><label for="employee-${loop.index}"><c:out value="${employee.departmentName}" /></label></td><td><label for="employee-${loop.index}"><c:out value="${employee.positionName}" /></label></td><td><label for="employee-${loop.index}"><c:out value="${employee.status eq 'WORK' ? '재직' : '퇴직'}" /></label></td></tr></c:forEach><c:if test="${empty employees}"><tr><td colspan="6" class="empty-row">선택할 사원이 없습니다.</td></tr></c:if></tbody></table></div><div class="employee-modal__actions"><button type="submit">사원선택</button><a href="#">선택취소</a></div></form></div>
		</div>
	</main>
	<%@ include file="/WEB-INF/view/common/footer.jspf" %>
</body>
</html>
