<%-- 조회 결과와 입력 양식을 표시하는 JSP 화면이다. --%>
<%-- 照会結果と入力フォームを表示するJSP画面である。 --%>
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="ui" tagdir="/WEB-INF/tags" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<!DOCTYPE html>
<html lang="ja-JP">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>人事管理>人事記録カード</title>
<link rel="stylesheet" href="${pageContext.request.contextPath}/css/employees/employees-record-card.css?v=20260820-5">
<link rel="stylesheet" href="${pageContext.request.contextPath}/css/common/payzon-ui.css?v=20260821-1">
</head>
<body>
    <%@ include file="/WEB-INF/view/common/header.jspf" %>
    <main class="page-content">
        <div class="record-page">
            <header class="page-heading"><div><p>人事管理</p><h1>人事記録カード</h1></div></header>

            <%-- 部署、役職、名前条件で、社員選択リストをサーバから再照会する。 --%>
            <form class="employee-search" action="${pageContext.request.contextPath}/employees/employee-card.do" method="get">
                <input type="hidden" name="mode" value="search">
                <select name="departmentId"><option value="">全体部署</option><c:forEach var="department" items="${departments}"><option value="${department.departmentId}" ${param.departmentId eq department.departmentId ? 'selected' : ''}><c:out value="${department.departmentName}" /></option></c:forEach></select>
                <select name="positionId"><option value="">全役職</option><c:forEach var="position" items="${positions}"><option value="${position.jobPositionId}" ${param.positionId eq position.jobPositionId ? 'selected' : ''}><c:out value="${position.jobPositionName}" /></option></c:forEach></select>
                <input name="keyword" value="<c:out value='${param.keyword}' />" placeholder="検索キーワードを入力">
                <button class="search-button" type="submit">検索</button>
                <a class="all-view" href="${pageContext.request.contextPath}/employees/employee-card.do?mode=all">全体を見る</a>
            </form>

            <%-- 選択されたEMPLOYEEと社員別詳細履歴を人事記録カード形式で出力する。 --%>
            <article class="record-sheet">
                <section class="identity-section">
                    <div class="photo-box"><c:choose><c:when test="${not empty selectedEmployee.photoPath}"><c:url var="employeePhotoUrl" value="${selectedEmployee.photoPath}" /><img src="<c:out value='${employeePhotoUrl}' />" alt="社員の写真"></c:when><c:otherwise><span>写真</span></c:otherwise></c:choose></div>
                    <dl class="record-number"><div><dt>社員番号</dt><dd><c:out value="${selectedEmployee.empNo}" /></dd></div><div><dt>入社日</dt><dd><fmt:formatDate value="${selectedEmployee.joinDate}" pattern="yyyy-MM-dd" /></dd></div><div><dt>退社日</dt><dd><fmt:formatDate value="${selectedEmployee.retireDate}" pattern="yyyy-MM-dd" /></dd></div></dl>
                    <dl class="identity-grid"><div><dt>氏名</dt><dd><c:out value="${selectedEmployee.empNameKr}" /></dd></div><div><dt>氏名（英語）</dt><dd><c:out value="${selectedEmployee.empNameEn}" /></dd></div><div><dt>住民登録番号</dt><dd><c:if test="${fn:length(selectedEmployee.juminNo) ge 6}"><c:out value="${fn:substring(selectedEmployee.juminNo, 0, 6)}-*******" /></c:if></dd></div><div><dt>社員区分</dt><dd><ui:code-label value="${selectedEmployee.empType}" /></dd></div><div class="wide"><dt>住所</dt><dd><c:out value="${selectedEmployee.address}" /></dd></div><div><dt>携帯電話</dt><dd><c:out value="${selectedEmployee.mobileNo}" /></dd></div><div><dt>連絡先</dt><dd><c:out value="${selectedEmployee.telNo}" /></dd></div><div class="wide"><dt>E-Mail</dt><dd><c:out value="${selectedEmployee.email}" /></dd></div></dl>
                </section>

                <div class="family-insurance-layout">
                    <section class="record-section"><h3>家族</h3><table><thead><tr><th>関係</th><th>氏名</th><th>住民登録番号</th><th>同居可</th></tr></thead><tbody><c:forEach var="family" items="${families}"><tr><td><c:out value="${family.relation}" /></td><td><c:out value="${family.depName}" /></td><td>******-*******</td><td><c:out value="${family.cohabitYn eq 'Y' ? '同居' : '別居'}" /></td></tr></c:forEach><c:if test="${empty families}"><c:forEach begin="1" end="4"><tr class="blank-row"><td></td><td></td><td></td><td></td></tr></c:forEach></c:if></tbody></table></section>
                    <section class="record-section"><h3>4大保険</h3><table><thead><tr><th>区分</th><th>記号番号</th><th>取得日</th><th>喪失日</th></tr></thead><tbody><c:forEach var="insurance" items="${insurances}"><tr><td><c:choose><c:when test="${insurance.insuranceType eq '국민연금'}">国民年金</c:when><c:when test="${insurance.insuranceType eq '건강보험'}">健康保険</c:when><c:when test="${insurance.insuranceType eq '고용보험'}">雇用保険</c:when><c:when test="${insurance.insuranceType eq '산재보험'}">労災保険</c:when><c:otherwise><c:out value="${insurance.insuranceType}" /></c:otherwise></c:choose></td><td><c:out value="${insurance.symbolNo}" /></td><td><fmt:formatDate value="${insurance.acquireDate}" pattern="yyyy-MM-dd" /></td><td><fmt:formatDate value="${insurance.lossDate}" pattern="yyyy-MM-dd" /></td></tr></c:forEach><c:if test="${empty insurances}"><c:forEach var="insuranceName" items="国民年金,健康保険,雇用保険,労災保険"><tr><td><c:out value="${insuranceName}" /></td><td></td><td></td><td></td></tr></c:forEach></c:if></tbody></table></section>
                </div>

                <section class="record-section"><h3>学歴</h3><table><thead><tr><th>学校名</th><th>入学年月</th><th>卒業年月</th><th>専攻</th><th></th></tr></thead><tbody><c:forEach var="education" items="${educations}"><tr><td><c:out value="${education.schoolName}" /></td><td><c:out value="${education.admissionYm}" /></td><td><c:out value="${education.gradYm}" /></td><td><c:out value="${education.majorName}" /></td><td><c:out value="${education.completeType}" /></td></tr></c:forEach><c:if test="${empty educations}"><c:forEach begin="1" end="2"><tr class="blank-row"><td></td><td></td><td></td><td></td><td></td></tr></c:forEach></c:if></tbody></table></section>
                <section class="record-section"><h3>兵役</h3><table><thead><tr><th>除隊区分</th><th>ミピル理由</th><th>軍別</th><th>最終クラス</th><th>病科</th><th>服務期間</th></tr></thead><tbody><tr><td><c:out value="${selectedEmployee.dischargeType}" /></td><td><c:out value="${selectedEmployee.milUnfinishedReason}" /></td><td><c:out value="${selectedEmployee.milBranch}" /></td><td><c:out value="${selectedEmployee.milRank}" /></td><td><c:out value="${selectedEmployee.milSpecialty}" /></td><td><fmt:formatDate value="${selectedEmployee.milServiceStart}" pattern="yyyy-MM-dd" /> ~ <fmt:formatDate value="${selectedEmployee.milServiceEnd}" pattern="yyyy-MM-dd" /></td></tr></tbody></table></section>
                <section class="record-section"><h3>職歴</h3><table><thead><tr><th>会社名</th><th>入社日</th><th>退社日</th><th>最終役職</th><th>担当業務</th></tr></thead><tbody><c:forEach var="career" items="${careers}"><tr><td><c:out value="${career.companyName}" /></td><td><fmt:formatDate value="${career.joinDate}" pattern="yyyy-MM-dd" /></td><td><fmt:formatDate value="${career.quitDate}" pattern="yyyy-MM-dd" /></td><td><c:out value="${career.finalPosition}" /></td><td><c:out value="${career.duty}" /></td></tr></c:forEach><c:if test="${empty careers}"><tr class="blank-row"><td colspan="5"></td></tr><tr class="blank-row"><td colspan="5"></td></tr></c:if></tbody></table></section>

                <div class="double-section">
                    <section class="record-section"><h3>資格/ライセンス</h3><table><thead><tr><th>種類</th><th>取得日</th><th>発行機関</th><th>備考</th></tr></thead><tbody><c:forEach var="license" items="${licenses}"><tr><td><c:out value="${license.licName}" /></td><td><fmt:formatDate value="${license.acqDate}" pattern="yyyy-MM-dd" /></td><td><c:out value="${license.issuer}" /></td><td><c:out value="${license.note}" /></td></tr></c:forEach><c:if test="${empty licenses}"><tr class="blank-row"><td colspan="4"></td></tr><tr class="blank-row"><td colspan="4"></td></tr></c:if></tbody></table></section>
                    <section class="record-section"><h3>語学能力</h3><table><thead><tr><th>外国語名</th><th>試験</th><th>認定スコア</th><th>取得日</th><th>読解</th><th>作文</th><th>絵画</th></tr></thead><tbody><c:forEach var="language" items="${languages}"><tr><td><c:out value="${language.langName}" /></td><td><c:out value="${language.testName}" /></td><td><c:out value="${language.score}" /></td><td><fmt:formatDate value="${language.acqDate}" pattern="yyyy-MM-dd" /></td><td><c:out value="${language.readingLevel}" /></td><td><c:out value="${language.writingLevel}" /></td><td><c:out value="${language.speakingLevel}" /></td></tr></c:forEach><c:if test="${empty languages}"><tr class="blank-row"><td colspan="7"></td></tr><tr class="blank-row"><td colspan="7"></td></tr></c:if></tbody></table></section>
                </div>

                <section class="record-section"><h3>教育事項</h3><table><thead><tr><th>教育区分</th><th>教育名</th><th>期間（から）</th><th>期間（まで）</th><th>教育機関</th><th>教育費</th><th>払い戻し教育費</th></tr></thead><tbody><c:forEach var="training" items="${trainings}"><tr><td><c:out value="${training.trainType}" /></td><td><c:out value="${training.trainName}" /></td><td><fmt:formatDate value="${training.startDate}" pattern="yyyy-MM-dd" /></td><td><fmt:formatDate value="${training.endDate}" pattern="yyyy-MM-dd" /></td><td><c:out value="${training.trainInstitute}" /></td><td><fmt:formatNumber value="${training.trainCost}" /></td><td><fmt:formatNumber value="${training.refundCost}" /></td></tr></c:forEach><c:if test="${empty trainings}"><tr class="blank-row"><td colspan="7"></td></tr><tr class="blank-row"><td colspan="7"></td></tr></c:if></tbody></table></section>
                <section class="record-section"><h3>罰則</h3><table><thead><tr><th>区分</th><th>商罰名</th><th>商罰権者</th><th>相反日</th><th>商罰内容</th><th>備考</th></tr></thead><tbody><c:forEach var="award" items="${awards}"><tr><td><c:out value="${award.rpType}" /></td><td><c:out value="${award.rpName}" /></td><td><c:out value="${award.rpAuthority}" /></td><td><fmt:formatDate value="${award.rpDate}" pattern="yyyy-MM-dd" /></td><td><c:out value="${award.rpContent}" /></td><td><c:out value="${award.note}" /></td></tr></c:forEach><c:if test="${empty awards}"><tr class="blank-row"><td colspan="6"></td></tr><tr class="blank-row"><td colspan="6"></td></tr></c:if></tbody></table></section>
                <section class="record-section"><h3>人事発令</h3><table><thead><tr><th>発令区分</th><th>発令日</th><th>部署</th><th>役職</th><th>役職と担当業務</th><th>備考</th></tr></thead><tbody><c:forEach var="appointment" items="${appointments}"><tr><td><c:out value="${appointment.appType}" /></td><td><fmt:formatDate value="${appointment.appDate}" pattern="yyyy-MM-dd" /></td><td><c:out value="${appointment.departmentName}" /></td><td><c:out value="${appointment.jobPositionName}" /></td><td><c:out value="${appointment.jobTitleDuty}" /></td><td><c:out value="${appointment.note}" /></td></tr></c:forEach><c:if test="${empty appointments}"><tr class="blank-row"><td colspan="6"></td></tr><tr class="blank-row"><td colspan="6"></td></tr></c:if></tbody></table></section>
                <section class="record-section"><h3>退職事項</h3><table><thead><tr><th>退職区分</th><th>退職日</th><th>退職理由</th><th>退職金</th><th>退職後の連絡先</th></tr></thead><tbody><tr><td><c:out value="${selectedEmployee.retireType}" /></td><td><fmt:formatDate value="${selectedEmployee.retireDate}" pattern="yyyy-MM-dd" /></td><td><c:out value="${selectedEmployee.retireReason}" /></td><td><c:if test="${not empty retirementCalculations}"><fmt:formatNumber value="${retirementCalculations[0].actualPayAmt}" /></c:if></td><td><c:out value="${selectedEmployee.afterRetireContact}" /></td></tr></tbody></table></section>
                <footer class="record-footer"><div class="record-footer__company"><strong><c:out value="${company.cmpnName}" /></strong><span><c:out value="${company.ceoTitle}" /> <c:out value="${company.ceoName}" /></span></div><div class="record-footer__stamp"><c:choose><c:when test="${not empty company.stampImgPath}"><img src="${pageContext.request.contextPath}<c:out value='${company.stampImgPath}' />" alt="会社印"></c:when><c:otherwise><span>会社印<br>未登録</span></c:otherwise></c:choose></div></footer>
            </article>

            <c:if test="${showEmployeeModal}"><div class="employee-modal employee-modal--visible" role="dialog" aria-modal="true" aria-labelledby="employee-modal-title"><a class="employee-modal__backdrop" href="${pageContext.request.contextPath}/employees/employee-card.do" aria-label="閉じる"></a><form class="employee-modal__panel" action="${pageContext.request.contextPath}/employees/employee-card.do" method="get"><div class="employee-modal__title"><h2 id="employee-modal-title">人事記録カードの社員を選択</h2><a href="${pageContext.request.contextPath}/employees/employee-card.do" aria-label="閉じる">×</a></div><div class="employee-modal__table"><table><thead><tr><th>区分</th><th>社員番号</th><th>氏名</th><th>部署</th><th>役職</th><th>ステータス</th></tr></thead><tbody><c:forEach var="employee" items="${employees}" varStatus="loop"><tr><td><label for="employee-${loop.index}"><input id="employee-${loop.index}" type="radio" name="employeeId" value="${employee.employeeId}" required><span><ui:code-label value="${employee.employmentType}" /></span></label></td><td><label for="employee-${loop.index}"><c:out value="${employee.employeeNo}" /></label></td><td><label for="employee-${loop.index}"><c:out value="${employee.name}" /></label></td><td><label for="employee-${loop.index}"><c:out value="${employee.departmentName}" /></label></td><td><label for="employee-${loop.index}"><c:out value="${employee.positionName}" /></label></td><td><label for="employee-${loop.index}"><c:out value="${employee.status eq 'WORK' ? '在職' : '退職'}" /></label></td></tr></c:forEach><c:if test="${empty employees}"><tr><td colspan="6" class="empty-row">選択する社員がいません。</td></tr></c:if></tbody></table></div><div class="employee-modal__actions"><button type="submit">社員を選択</button><a href="${pageContext.request.contextPath}/employees/employee-card.do">選択解除</a></div></form></div></c:if>

            <c:if test="${not empty searchConditionMessage}"><div class="employee-modal employee-modal--visible" role="alertdialog" aria-modal="true" aria-labelledby="search-condition-message"><a class="employee-modal__backdrop" href="${pageContext.request.contextPath}/employees/employee-card.do" aria-label="閉じる"></a><div class="employee-modal__panel employee-modal__panel--notice"><p id="search-condition-message" class="employee-modal__notice"><ui:message-label value="${searchConditionMessage}" /></p><div class="employee-modal__actions"><a class="notice-confirm" href="${pageContext.request.contextPath}/employees/employee-card.do">確認</a></div></div></div></c:if>
        </div>
    </main>
    <%@ include file="/WEB-INF/view/common/footer.jspf" %>
</body>
</html>
