package erp.retirement.service;

import java.sql.Connection;import java.sql.SQLException;import java.text.SimpleDateFormat;import java.util.ArrayList;import java.util.List;
import erp.employees.dao.EmployeeDao;import erp.employees.model.Employee;import erp.retirement.dao.RetirementCalculationDao;import erp.retirement.dao.RetirementIncomeEntryDao;import erp.retirement.dto.RetirementBenefitListItem;import erp.retirement.dto.RetirementPayslip;import erp.retirement.model.RetirementCalculation;import erp.retirement.model.RetirementIncomeEntry;import erp.settings.dao.CompanyDao;import erp.settings.dao.DepartmentDao;import erp.settings.dao.JobPositionDao;import jdbc.connection.ConnectionProvider;

// 저장된 퇴직급여 마스터와 산정자료를 명세서 한 장으로 조합하는 Service
public class RetirementPayslipService {
	private final RetirementCalculationDao dao=RetirementCalculationDao.getInstance();
	public List<Integer> getPaymentYears(){int y=java.time.LocalDate.now().getYear();List<Integer> r=new ArrayList<>();for(int i=y+1;i>=y-5;i--)r.add(i);return r;}
	public PayslipData getData(int year,String keyword,Integer id){try(Connection c=ConnectionProvider.getConnection()){PayslipData d=new PayslipData();d.items=dao.selectBenefitList(c,year);if(keyword!=null&&!keyword.trim().isEmpty())d.items.removeIf(x->!x.getEmployeeName().contains(keyword.trim()));d.company=CompanyDao.getInstance().selectById(c,1);if(id==null&&!d.items.isEmpty())id=d.items.get(0).getCalculationId();if(id!=null)d.selected=make(c,id);return d;}catch(SQLException e){throw new RuntimeException(e);}}
	private RetirementPayslip make(Connection c,int id)throws SQLException{RetirementCalculation r=dao.selectById(c,id);if(r==null)return null;Employee e=EmployeeDao.getInstance().selectById(c,r.getEmployeeId());SimpleDateFormat f=new SimpleDateFormat("yyyy-MM-dd");RetirementPayslip p=new RetirementPayslip();p.setCalculationId(id);p.setEmployeeId(e.getEmployeeId());p.setSettlementType(r.getCalcType());p.setEmployeeName(e.getEmpNameKr());p.setJoinDate(f.format(r.getCalcStartDate()));p.setRetirementDate(f.format(r.getRetireDate()));if(e.getDepartmentId()!=null)p.setDepartmentName(DepartmentDao.getInstance().selectById(c,e.getDepartmentId()).getDepartmentName());if(e.getJobPositionId()!=null)p.setPositionName(JobPositionDao.getInstance().selectById(c,e.getJobPositionId()).getJobPositionName());p.setServiceDays(r.getServiceDays());p.setCompensation(r.getCompensationAmt());p.setDismissalAllowance(r.getDismissalAmt());p.setThreeMonthTotal(r.getThreeMonthTotal());p.setDailyAverage(r.getAvgDayWage());p.setDailyOrdinary(r.getOrdinaryDayWage());p.setRetirementIncome(r.getRetireIncome());p.setIncomeTax(r.getIncomeTax());p.setLocalIncomeTax(r.getLocalIncomeTax());p.setOtherDeduction(r.getOtherDeductAmt());p.setDeductionTotal(r.getIncomeTax()+r.getLocalIncomeTax()+r.getSpecialRuralTax()+r.getOtherDeductAmt());p.setNetPayment(r.getActualPayAmt());for(RetirementIncomeEntry x:RetirementIncomeEntryDao.getInstance().selectByCalcId(c,id)){if(x.isSalaryData()){RetirementPayslip.SalaryDetail s=new RetirementPayslip.SalaryDetail();s.setStartDate(f.format(x.getPeriodStartDate()));s.setEndDate(f.format(x.getPeriodEndDate()));s.setDays(x.getCalcDays()==null?0:x.getCalcDays());s.setAmount(x.getAmount());p.getSalaryDetails().add(s);p.setSalaryDaysTotal(p.getSalaryDaysTotal()+Math.round(s.getDays()));p.setSalaryTotal(p.getSalaryTotal()+s.getAmount());}else{RetirementPayslip.OtherIncome o=new RetirementPayslip.OtherIncome();o.setItemName(x.getItemName());o.setAnnualAmount(x.getAmount());o.setThreeMonthAmount(x.getThreeMonthAmount());p.getOtherIncomes().add(o);}}while(p.getSalaryDetails().size()<4)p.getSalaryDetails().add(new RetirementPayslip.SalaryDetail());return p;}
	public static class PayslipData{private List<RetirementBenefitListItem> items;private RetirementPayslip selected;private Object company;public List<RetirementBenefitListItem> getItems(){return items;}public RetirementPayslip getSelected(){return selected;}public Object getCompany(){return company;}}
}
