<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html lang="ko">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>인사관리 &gt; 인사기록카드</title>
<link rel="stylesheet" href="${pageContext.request.contextPath}/css/hr/employee-record-card.css">
<link rel="stylesheet" href="${pageContext.request.contextPath}/css/common/payzon-ui.css">
</head>
<body>
	<%@ include file="/WEB-INF/view/common/header.jspf" %>
	<main class="page-content">
		<div class="record-page">
			<header class="page-heading"><div><p>인사관리</p><h1>인사기록카드</h1></div></header>

			<form class="employee-search" action="${pageContext.request.contextPath}/personnel/employee-card.do" method="get">
				<select name="departmentId"><option value="">전체 부서</option><c:forEach var="department" items="${departments}"><option value="${department.departmentId}" ${param.departmentId eq department.departmentId ? 'selected' : ''}><c:out value="${department.departmentName}" /></option></c:forEach></select>
				<select name="positionId"><option value="">전체 직위</option><c:forEach var="position" items="${positions}"><option value="${position.positionId}" ${param.positionId eq position.positionId ? 'selected' : ''}><c:out value="${position.positionName}" /></option></c:forEach></select>
				<input name="keyword" value="<c:out value='${param.keyword}' />" placeholder="검색어 입력">
				<a class="search-button" href="#employee-select-modal">검색</a>
				<a class="all-view" href="${pageContext.request.contextPath}/personnel/employee-card.do">전체보기</a>
			</form>

			<article class="record-sheet">
				<section class="identity-section">
					<div class="photo-box"><c:choose><c:when test="${not empty selectedEmployee.photoUrl}"><img src="<c:out value='${selectedEmployee.photoUrl}' />" alt="사원사진"></c:when><c:otherwise><span>사진</span></c:otherwise></c:choose></div>
					<dl class="record-number"><div><dt>사원번호</dt><dd><c:out value="${selectedEmployee.employeeNo}" /></dd></div><div><dt>입사일</dt><dd><c:out value="${selectedEmployee.joinDate}" /></dd></div><div><dt>퇴사일</dt><dd><c:out value="${selectedEmployee.retirementDate}" /></dd></div></dl>
					<dl class="identity-grid"><div><dt>성명(한글)</dt><dd><c:out value="${selectedEmployee.name}" /></dd></div><div><dt>성명(영문)</dt><dd><c:out value="${selectedEmployee.englishName}" /></dd></div><div><dt>주민등록번호</dt><dd><c:out value="${selectedEmployee.maskedResidentNo}" /></dd></div><div><dt>사원구분</dt><dd><c:out value="${selectedEmployee.employmentType}" /></dd></div><div class="wide"><dt>주소</dt><dd><c:out value="${selectedEmployee.address}" /></dd></div><div><dt>휴대전화</dt><dd><c:out value="${selectedEmployee.mobile}" /></dd></div><div><dt>연락처</dt><dd><c:out value="${selectedEmployee.phone}" /></dd></div><div class="wide"><dt>E-Mail</dt><dd><c:out value="${selectedEmployee.email}" /></dd></div></dl>
				</section>

				<div class="family-insurance-layout">
					<section class="record-section"><h3>가족사항</h3><table><thead><tr><th>관계</th><th>성명</th><th>주민등록번호</th><th>동거여부</th></tr></thead><tbody><c:forEach var="family" items="${families}"><tr><td><c:out value="${family.relationship}" /></td><td><c:out value="${family.name}" /></td><td><c:out value="${family.maskedResidentNo}" /></td><td><c:out value="${family.liveTogetherYn eq 'Y' ? '동거' : '비동거'}" /></td></tr></c:forEach><c:if test="${empty families}"><c:forEach begin="1" end="4"><tr class="blank-row"><td></td><td></td><td></td><td></td></tr></c:forEach></c:if></tbody></table></section>
					<section class="record-section"><h3>4대보험</h3><table><thead><tr><th>구분</th><th>기호번호</th><th>취득일</th><th>상실일</th></tr></thead><tbody><c:forEach var="insurance" items="${insurances}"><tr><td><c:out value="${insurance.insuranceName}" /></td><td><c:out value="${insurance.insuranceNo}" /></td><td><c:out value="${insurance.acquireDate}" /></td><td><c:out value="${insurance.lossDate}" /></td></tr></c:forEach><c:if test="${empty insurances}"><c:forEach var="insuranceName" items="국민연금,건강보험,고용보험,산재보험"><tr><td><c:out value="${insuranceName}" /></td><td></td><td></td><td></td></tr></c:forEach></c:if></tbody></table></section>
				</div>

				<section class="record-section"><h3>학력</h3><table><thead><tr><th>학교명</th><th>입학년월</th><th>졸업년월</th><th>전공</th><th>이수</th></tr></thead><tbody><c:forEach var="education" items="${educations}"><tr><td><c:out value="${education.schoolName}" /></td><td><c:out value="${education.admissionDate}" /></td><td><c:out value="${education.graduationDate}" /></td><td><c:out value="${education.major}" /></td><td><c:out value="${education.completionType}" /></td></tr></c:forEach><c:if test="${empty educations}"><c:forEach begin="1" end="2"><tr class="blank-row"><td></td><td></td><td></td><td></td><td></td></tr></c:forEach></c:if></tbody></table></section>
				<section class="record-section"><h3>병역</h3><table><thead><tr><th>제대구분</th><th>미필사유</th><th>군별</th><th>최종계급</th><th>병과</th><th>복무기간</th></tr></thead><tbody><tr><td><c:out value="${military.dischargeType}" /></td><td><c:out value="${military.exemptionReason}" /></td><td><c:out value="${military.militaryType}" /></td><td><c:out value="${military.finalRank}" /></td><td><c:out value="${military.branch}" /></td><td><c:out value="${military.serviceStartDate}" /> ~ <c:out value="${military.serviceEndDate}" /></td></tr></tbody></table></section>
				<section class="record-section"><h3>경력</h3><table><thead><tr><th>회사명</th><th>입사일자</th><th>퇴사일자</th><th>최종직위</th><th>담당업무</th></tr></thead><tbody><c:forEach var="career" items="${careers}"><tr><td><c:out value="${career.companyName}" /></td><td><c:out value="${career.joinDate}" /></td><td><c:out value="${career.retirementDate}" /></td><td><c:out value="${career.finalPosition}" /></td><td><c:out value="${career.duty}" /></td></tr></c:forEach><c:if test="${empty careers}"><tr class="blank-row"><td colspan="5"></td></tr><tr class="blank-row"><td colspan="5"></td></tr></c:if></tbody></table></section>

				<div class="double-section">
					<section class="record-section"><h3>자격/면허</h3><table><thead><tr><th>종류</th><th>취득일</th><th>발행기관</th><th>비고</th></tr></thead><tbody><c:forEach var="license" items="${licenses}"><tr><td><c:out value="${license.licenseName}" /></td><td><c:out value="${license.acquireDate}" /></td><td><c:out value="${license.issuer}" /></td><td><c:out value="${license.note}" /></td></tr></c:forEach><c:if test="${empty licenses}"><tr class="blank-row"><td colspan="4"></td></tr><tr class="blank-row"><td colspan="4"></td></tr></c:if></tbody></table></section>
					<section class="record-section"><h3>어학능력</h3><table><thead><tr><th>외국어명</th><th>시험</th><th>공인점수</th><th>취득일</th><th>독해</th><th>작문</th><th>회화</th></tr></thead><tbody><c:forEach var="language" items="${languages}"><tr><td><c:out value="${language.languageName}" /></td><td><c:out value="${language.testName}" /></td><td><c:out value="${language.score}" /></td><td><c:out value="${language.acquireDate}" /></td><td><c:out value="${language.readingLevel}" /></td><td><c:out value="${language.writingLevel}" /></td><td><c:out value="${language.speakingLevel}" /></td></tr></c:forEach><c:if test="${empty languages}"><tr class="blank-row"><td colspan="7"></td></tr><tr class="blank-row"><td colspan="7"></td></tr></c:if></tbody></table></section>
				</div>

				<section class="record-section"><h3>교육사항</h3><table><thead><tr><th>교육구분</th><th>교육명</th><th>기간(부터)</th><th>기간(까지)</th><th>교육기관</th><th>교육비</th><th>환급교육비</th></tr></thead><tbody><c:forEach var="training" items="${trainings}"><tr><td><c:out value="${training.trainingType}" /></td><td><c:out value="${training.trainingName}" /></td><td><c:out value="${training.startDate}" /></td><td><c:out value="${training.endDate}" /></td><td><c:out value="${training.organization}" /></td><td><c:out value="${training.cost}" /></td><td><c:out value="${training.refundAmount}" /></td></tr></c:forEach><c:if test="${empty trainings}"><tr class="blank-row"><td colspan="7"></td></tr><tr class="blank-row"><td colspan="7"></td></tr></c:if></tbody></table></section>
				<section class="record-section"><h3>상벌사항</h3><table><thead><tr><th>구분</th><th>상벌명</th><th>상벌권자</th><th>상벌일자</th><th>상벌내용</th><th>비고</th></tr></thead><tbody><c:forEach var="award" items="${awards}"><tr><td><c:out value="${award.awardType}" /></td><td><c:out value="${award.awardName}" /></td><td><c:out value="${award.awarder}" /></td><td><c:out value="${award.awardDate}" /></td><td><c:out value="${award.content}" /></td><td><c:out value="${award.note}" /></td></tr></c:forEach><c:if test="${empty awards}"><tr class="blank-row"><td colspan="6"></td></tr><tr class="blank-row"><td colspan="6"></td></tr></c:if></tbody></table></section>
				<section class="record-section"><h3>인사발령</h3><table><thead><tr><th>발령구분</th><th>발령일자</th><th>부서</th><th>직위</th><th>직책 및 담당업무</th><th>비고</th></tr></thead><tbody><c:forEach var="appointment" items="${appointments}"><tr><td><c:out value="${appointment.appointmentType}" /></td><td><c:out value="${appointment.appointmentDate}" /></td><td><c:out value="${appointment.departmentName}" /></td><td><c:out value="${appointment.positionName}" /></td><td><c:out value="${appointment.duty}" /></td><td><c:out value="${appointment.note}" /></td></tr></c:forEach><c:if test="${empty appointments}"><tr class="blank-row"><td colspan="6"></td></tr><tr class="blank-row"><td colspan="6"></td></tr></c:if></tbody></table></section>
				<section class="record-section"><h3>퇴직사항</h3><table><thead><tr><th>퇴직구분</th><th>퇴직일자</th><th>퇴직사유</th><th>퇴직금</th><th>퇴직 후 연락처</th></tr></thead><tbody><tr><td><c:out value="${retirement.retirementType}" /></td><td><c:out value="${retirement.retirementDate}" /></td><td><c:out value="${retirement.reason}" /></td><td><c:out value="${retirement.retirementPay}" /></td><td><c:out value="${retirement.contactAfterRetirement}" /></td></tr></tbody></table></section>
				<footer class="record-footer"><label><input type="checkbox" name="showCeo" checked> 대표자 표기</label><div class="record-footer__company"><strong><c:out value="${company.companyName}" /></strong><span>대표이사 <c:out value="${company.ceoName}" /></span></div><div class="record-footer__stamp"><c:choose><c:when test="${not empty company.stampUrl}"><img src="<c:out value='${company.stampUrl}' />" alt="회사 도장"></c:when><c:otherwise><span>회사 도장을<br>넣어주세요</span></c:otherwise></c:choose></div></footer>
			</article>

			<div id="employee-select-modal" class="employee-modal" role="dialog" aria-modal="true" aria-labelledby="employee-modal-title"><a class="employee-modal__backdrop" href="#" aria-label="닫기"></a><form class="employee-modal__panel" action="${pageContext.request.contextPath}/personnel/employee-card.do" method="get"><div class="employee-modal__title"><h2 id="employee-modal-title">인사기록카드 사원선택</h2><a href="#" aria-label="닫기">×</a></div><div class="employee-modal__table"><table><thead><tr><th>구분</th><th>사원번호</th><th>성명</th><th>부서</th><th>직위</th><th>상태</th></tr></thead><tbody><c:forEach var="employee" items="${employees}" varStatus="loop"><tr><td><label for="employee-${loop.index}"><input id="employee-${loop.index}" type="radio" name="employeeId" value="${employee.employeeId}" required><span><c:out value="${employee.employmentType}" /></span></label></td><td><label for="employee-${loop.index}"><c:out value="${employee.employeeNo}" /></label></td><td><label for="employee-${loop.index}"><c:out value="${employee.name}" /></label></td><td><label for="employee-${loop.index}"><c:out value="${employee.departmentName}" /></label></td><td><label for="employee-${loop.index}"><c:out value="${employee.positionName}" /></label></td><td><label for="employee-${loop.index}"><c:out value="${employee.status eq 'WORK' ? '재직' : '퇴직'}" /></label></td></tr></c:forEach><c:if test="${empty employees}"><tr><td colspan="6" class="empty-row">선택할 사원이 없습니다.</td></tr></c:if></tbody></table></div><div class="employee-modal__actions"><button type="submit">사원선택</button><a href="#">선택취소</a></div></form></div>
		</div>
	</main>
	<%@ include file="/WEB-INF/view/common/footer.jspf" %>
</body>
</html>
