# ============================================================
# Home Management
# ============================================================
/home.do=erp.home.command.HomeHandler

# ============================================================
# Attendance Management
# ============================================================
# /attend/manage.do=erp.attendance.command.AttendRecordManageRecordHandler
/attendance/day-worker-management.do=erp.attendance.command.DayWorkerManagementHandler
/attendance/day-worker-inquiry.do=erp.attendance.command.DayWorkerInquiryHandler
/attendance/project-manage.do=erp.attendance.command.ProjectManagerHandler
# ============================================================
# Employees Management
# ============================================================
/employees/employees.do=erp.employees.command.EmployeeListHandler
/employees/employee-action.do=erp.employees.command.EmployeeListHandler
/employees/employee-columns.do=erp.employees.command.EmployeeListHandler
/employees/employee-card.do=erp.employees.command.EmployeeRecordCardHandler
/employees/certificate.do=erp.employees.command.CertificateIssueHandler
/employees/certificate-issue.do=erp.employees.command.CertificateIssueHandler
/employees/certificate-register.do=erp.employees.command.CertificateRegisterHandler
/employees/certificate-register-delete.do=erp.employees.command.CertificateRegisterHandler

# ============================================================
# Retirement Management
# ============================================================
/retirement/process.do=erp.retirement.command.RetirementProcessHandler
/retirement/benefit.do=erp.retirement.command.RetirementBenefitHandler
/retirement/benefit/employee-search.do=erp.retirement.command.RetirementBenefitHandler
/retirement/benefit/new.do=erp.retirement.command.RetirementBenefitHandler
/retirement/benefit/calculate.do=erp.retirement.command.RetirementBenefitHandler
/retirement/benefit/load-pay.do=erp.retirement.command.RetirementBenefitHandler
/retirement/benefit/save.do=erp.retirement.command.RetirementBenefitHandler
/retirement/benefit/delete.do=erp.retirement.command.RetirementBenefitHandler
/retirement/benefit/delete-all.do=erp.retirement.command.RetirementBenefitHandler
/retirement/payslip.do=erp.retirement.command.RetirementPayslipHandler

# ============================================================
# Payroll Management
# ============================================================
/payroll/management.do=erp.payroll.command.PayrollManagementHandler
/payroll/management/save.do=erp.payroll.command.PayrollManagementHandler
/payroll/management/employees/add.do=erp.payroll.command.PayrollManagementHandler
/payroll/management/employees/delete.do=erp.payroll.command.PayrollManagementHandler
/payroll/management/load-previous.do=erp.payroll.command.PayrollManagementHandler
/payroll/management/give-item/save.do=erp.payroll.command.PayrollManagementHandler
/payroll/management/deduction-item/save.do=erp.payroll.command.PayrollManagementHandler
/payroll/day-worker-management.do=erp.payroll.command.DayWorkerPayrollHandler
/payroll/day-worker/save.do=erp.payroll.command.DayWorkerPayrollHandler
/payroll/day-worker/employees/add.do=erp.payroll.command.DayWorkerPayrollHandler
/payroll/day-worker/employees/delete.do=erp.payroll.command.DayWorkerPayrollHandler
/payroll/register.do=erp.payroll.command.PayrollRegisterHandler
/payroll/register/detail.do=erp.payroll.command.PayrollRegisterHandler
/payroll/register/delete.do=erp.payroll.command.PayrollRegisterHandler
/payroll/payslip.do=erp.payroll.command.PayrollPayslipHandler
/payroll/employee-history.do=erp.payroll.command.EmployeePayrollHistoryHandler
/payroll/item-ledger.do=erp.payroll.command.PayrollItemLedgerHandler
/payroll/four-insurance.do=erp.payroll.command.FourInsuranceHandler
/payroll-stats/annual.do=erp.payrollstats.command.AnnualPayrollStatHandler
/payroll-stats/monthly.do=erp.payrollstats.command.MonthlyPayrollStatHandler
/payroll-stats/composition.do = erp.payrollstats.command.PayrollItemCompositionStatHandler
# ============================================================
# Settings Management
# ============================================================
/settings/user-info.do=erp.settings.command.UserInfoSettingsHandler
/settings/register1.do=erp.settings.command.EmployeeRegister1Handler
/settings/register2.do=erp.settings.command.EmployeeRegister2Handler
/settings/attendance.do=erp.settings.command.AttendanceSettingsHandler
/settings/leave-item.do=erp.settings.command.LeaveItemHandler
/settings/attend-item.do=erp.settings.command.AttendanceItemHandler
/settings/attend-group.do=erp.settings.command.AttendanceGroupHandler
/settings/employee-leave.do=erp.settings.command.EmployeeLeaveHandler
/settings/pay-item.do=erp.settings.command.PayItemHandler
/settings/deduction-item.do=erp.settings.command.DeductItemHandler
